version: '3'
name: minha-api

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADMIN_PASSWORD=admin
    networks:
      - minha-rede

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "@#$%&*123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    depends_on:
      - seq
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - minha-rede
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - sql-server
    networks:
      - minha-rede
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - minha-rede

volumes:
  db-data:
    driver: local

networks:
  minha-rede:
    driver: bridge